[package]
name = "bittorent"
version = "0.1.0"
authors = ["mawalu <martin@mawalabs.de>"]
edition = "2018"

[dependencies]
chrono = "0.4.11"
hex = "0.4"
sha-1 = "0.8.2"
rand = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_bencode = "^0.2.1"
serde_derive = "^1.0.0"